### ISSUE TITLE
Ability to fetch up to a certain depth, or/and up to a certain revision

### ISSUE THREAD

**Issue by kerrmarin** [srinivasupadhya/git-cmd#9]
Hey,

It would be great to be able to fetch up until a given revision, something like: `fetchUpToAtLeastRevision(String revision)` or `fetch(Integer depth)`. This would enable shallow clones on https://github.com/ashwanthkumar/gocd-build-github-pull-requests/pull/67#issuecomment-205375623

**Comment by ashwanthkumar** [comment]
@kerrmarin I'm no longer using this module in the project. Please open an issue against https://github.com/ashwanthkumar/git-cmd.
